### PR TITLE
Exclude JIT-related declarations more aggressively

### PR DESCRIPTION
**Pull request by JesseTG**
This reduces the risk of linker errors occurring when building on ARM without the JIT.

### CODE REVIEW

**Comment by Adamillo** [comment]
That makes me curious. Does this mean that someone could now theoretically use melonDS on ARMv7 aka 32-bit ARM with no JIT?

**Comment by Adamillo** [comment]
I see. The reason I ask is that on platforms like x86_32 you can use melonDS with the JIT disabled. I'd imagine that you'd be able to do the same with ARM32 now that the linker errors are fixed

**Comment by RSDuck** [comment]
> That makes me curious. Does this mean that someone could now theoretically use melonDS on ARMv7 aka 32-bit ARM with no JIT?

you could already do that before. Besides maybe some small slip up the JIT is fully disableable

**Comment by JesseTG** [comment]
And this PR fixes some sources of small slip-ups.

**Pull request merged**
