### PR TITLE
Audio interpolation rework

### PR DESCRIPTION
**Pull request by Powerlated**
See #1521

### CODE REVIEW

**Comment by nadiaholmquist** [comment]
Ah lol the bitrate thing, I asked in the Discord if anyone knew what the correct term was but didn't really get a response, so that's what ended up being committed. You can probably tell I'm not the most knowledgeable about audio...

Only realized the mistake after the release with that in it was shipped, oops.

**Comment by Arisotura** [comment]
why is this named 'Full audio rework' when it's just about changing one term

I'm all for using the proper terms, tho; just want to hear about this bit, are there more changes planned to this pull request? should we wait before merging it?

**Comment by nadiaholmquist** [comment]
See the issue linked in the OP, I think this is work in progress.

**Comment by Arisotura** [comment]
'aight -- I'll wait for their instructions before merging this

**Comment by RayyanAnsari** [comment]
probably a good idea to mark this as a draft

**Pull request closed without merging**
