### PR TITLE
CI: Simplify Windows build workflow

### PR DESCRIPTION
**Pull request by Biswa96**
* Use pacboy to download dependencies instead of a separate step.
* Use ninja instead of make because ninja is faster and native in msys2.
* Use cmake options instead of changing working directory every steps.

### CODE REVIEW

**Comment by nadiaholmquist** [comment]
Look good to me.

Do you have a link to where these extra properties you are using are documented? I had no idea about them.

**Comment by Biswa96** [comment]
msys2's docs: https://www.msys2.org/docs/ci/
GitHub Marketplace docs: https://github.com/marketplace/actions/setup-msys2
msys2-setup repo: https://github.com/msys2/setup-msys2

**Comment by RayyanAnsari** [comment]
This PR looks good - it makes the workflow file simpler as well.

Though, with Ninja is there supposed to be no colour in the output?

**Comment by Biswa96** [comment]
> with Ninja is there supposed to be no colour in the output?

Yes. There are some hacks https://medium.com/@alasher/colored-c-compiler-output-with-ninja-clang-gcc-10bfe7f2b949. But it is not msys2 specific.

**Pull request closed without merging**
